#!/bin/sh

CLANG=clang
CLANG_FLAGS="-target mips-unknown-linux-gnu -O0 -emit-llvm -I../include -isystem../libc -nostdinc"

# modify this to point to your llc. use absolute paths.
LLC=/home/hob/Programs/llvm-src/llvm-3.9.0.src/build/bin-sw/llc
LLC_FLAGS="-march=cpu0el -relocation-model=static"
LLD=/home/hob/Programs/llvm-src/llvm-3.9.0.src/build/bin-sw/ld.lld

C_EXT=".c"
NO_EXT=""

BUILD_DIR="../build"

cd $BUILD_DIR
${LLD} *.o -T ../script.ld -e main -o a.out
objdump -s a.out > a.out.od.s

